version: '3'
services:
  web:
    ports:
      - '4733:3000'
    environment:
      - NODE_ENV=production
    network_mode: bridge
    restart: unless-stopped
  mongo:
    network_mode: bridge
    restart: unless-stopped
  imaginary:
    network_mode: bridge
    restart: unless-stopped
  redis:
    network_mode: bridge
    restart: unless-stopped
